from flask import Blueprint

from .guess_games import guess_games_controller
from .daily_guess_games import daily_guess_games_controller
from .platforms import platforms_controller
from .operating_systems import operating_systems_controller
from .profiles import profiles_controller
from .products.router import products_controller
from .tags import tags_controller
from .service_profiles import service_profiles_controller
from .affiliates import affiliates_controller
from .affiliate_reviews import affiliate_reviews_controller
from .platform_products import platform_products_controller
from .affiliate_platform_products import affiliate_platform_products_controller

admin_controller = Blueprint('admin', __name__, url_prefix='/admin')

admin_controller.register_blueprint(platforms_controller)
admin_controller.register_blueprint(operating_systems_controller)
admin_controller.register_blueprint(profiles_controller)
admin_controller.register_blueprint(products_controller)
admin_controller.register_blueprint(guess_games_controller)
admin_controller.register_blueprint(daily_guess_games_controller)
admin_controller.register_blueprint(platform_products_controller)
admin_controller.register_blueprint(affiliate_platform_products_controller)
admin_controller.register_blueprint(tags_controller)
admin_controller.register_blueprint(service_profiles_controller)
admin_controller.register_blueprint(affiliates_controller)
admin_controller.register_blueprint(affiliate_reviews_controller)
