name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m testicles.cli -t unit

  integration:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7.0

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_NAMESPACE: ${{ secrets.AUTH0_NAMESPACE }}
          AUTH0_ROLES: ${{ secrets.AUTH0_ROLES }}
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_SERVICE_ACCOUNT: ${{ secrets.FB_SERVICE_ACCOUNT }}
        run: |
          python -m testicles.cli -t integration