name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m testicles.cli -t unit

  integration:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-replica-set: test-rs
          mongodb-version: 7.0

      - name: Migrate DB
        run: |
          pymongo-migrate migrate -u "${{ secrets.MONGO_URI }}" -c migrations -m migrations

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          FB_NAMESPACE: ${{ vars.FB_NAMESPACE }}
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_SERVICE_ACCOUNT: ${{ secrets.FB_SERVICE_ACCOUNT }}
          FB_M2M_SECRET_KEY: ${{ vars.FB_M2M_SECRET_KEY }}
        run: |
          python -m testicles.cli -t integration