name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          python -m testicles.cli -t unit

  integration:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7.0

      - name: Restore cached Auth0 tokens
        id: restore-auth0-cached-tokens
        uses: actions/cache@v4
        with:
          path: ${{ vars.AUTH0_CACHE_DIR }}
          key: tokens

      - name: Print tokens
        env:
          AUTH0_CACHE_DIR: ${{ vars.AUTH0_CACHE_DIR }}
        run: |
          cat "$AUTH0_CACHE_DIR/tokens"

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_NAMESPACE: ${{ secrets.AUTH0_NAMESPACE }}
          AUTH0_ROLES: ${{ secrets.AUTH0_ROLES }}
          AUTH0_CACHE_DIR: ${{ vars.AUTH0_CACHE_DIR }}
        run: |
          python -m testicles.cli -t integration

      - name: Cache Auth0 tokens
        id: cache-auth0-tokens
        uses: actions/cache@v4
        with:
          path: ${{ vars.AUTH0_CACHE_DIR }}
          key: tokens
